### ISSUE TITLE
Manifest name not match a site

### ISSUE THREAD

**Issue by kaiwanyawit-chawankul** [dotnetthailand/dotnetthailand.github.io#102]
Now it use a name and short name as **BooGi** for PWA

<img width="131" alt="Screen Shot 2564-08-03 at 08 45 51" src="https://user-images.githubusercontent.com/80441020/127944934-fa38a4f4-fecf-4ed4-9af8-37151358c564.png">
<img width="1792" alt="Screen Shot 2564-08-03 at 08 47 18" src="https://user-images.githubusercontent.com/80441020/127944940-a40edef7-03a5-4991-8901-4cafffa95a1a.png">

**Comment by kaiwanyawit-chawankul** [comment]
CC @aaronamm Please check this

Is it fixed by this commit? https://github.com/dotnetthailand/dotnetthailand.github.io/blob/32e82bd7c9949f895e3f67ca22ec2b15b3ceb7c3/config/config.yml

**Comment by kaiwanyawit-chawankul** [comment]
I found the source of this error. the pwa use config from this section of `config/config.yml`
<img width="384" alt="Screen Shot 2564-08-04 at 22 19 13" src="https://user-images.githubusercontent.com/80441020/128207663-c9966950-f141-4b95-8215-afb4becaac7b.png">

@aaronamm  You have 2 options for this change
- move the config to pwa section
- modify this file `src/utils/config-pwa.js` to use data from `config` directly

<img width="800" alt="Screen Shot 2564-08-04 at 22 19 25" src="https://user-images.githubusercontent.com/80441020/128207641-3540e7d6-cd8c-4379-91fa-03ecbf2a8902.png">

**Comment by mildronize** [comment]
@kaiwanyawit-chawankul Thank for your suggestion.

We will workaround the manifest info of the site, if you know how to fix it, feel free to send the PR.

**Comment by kaiwanyawit-chawankul** [comment]
@mildronize I tried but I can't create a branch. I used fork on my previous PR. 
<img width="948" alt="Screen Shot 2564-08-05 at 21 55 19" src="https://user-images.githubusercontent.com/80441020/128371922-577399f1-3462-47dd-b10a-9049108dc294.png">


Line 87 and 88 is the fix for this issue
![image](https://user-images.githubusercontent.com/80441020/128371975-a91d8676-3caf-410d-9427-24a8235f45bb.png)

**Comment by mildronize** [comment]
@kaiwanyawit-chawankul I see, Do u read this doc? https://github.com/dotnetthailand/dotnetthailand.github.io/blob/main/CONTRIBUTING.md#3-open-a-pull-request

You cannot push to main branch of this project directly, you should fork this project and create a new branch, Then create a PR. 
Please follow this doc: https://github.com/dotnetthailand/dotnetthailand.github.io/blob/main/CONTRIBUTING.md#3-open-a-pull-request

**Comment by kaiwanyawit-chawankul** [comment]
@mildronize @aaronamm please check my PR https://github.com/dotnetthailand/dotnetthailand.github.io/pull/111

**Comment by mildronize** [comment]
@kaiwanyawit-chawankul Yes, I've merged. Look good.

![image](https://user-images.githubusercontent.com/3647850/128439637-2399d47e-7725-4820-9867-ae5423e71a29.png)
