### ISSUE TITLE
Clicking an author's name on each page will show a lit of all pages that author creates.

### ISSUE THREAD

**Issue by aaronamm** [dotnetthailand/dotnetthailand.github.io#110]
Here is the workflow:
- You are on any page.
- Each page has an author's name of that page.
- An author is a link.
- Clicking an author's name will be redirect to a lit of all pages that author creates.

This feature is useful for an author that later he/she can use it for his/her portfolio.

**Comment by mildronize** [comment]
@aaronamm Interesting issue, 

Here is the related API: https://api.github.com/repos/dotnetthailand/dotnetthailand.github.io/commits?author=[username]

**Comment by mildronize** [comment]
Possible Component UI by Fluent UI

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

![image](https://user-images.githubusercontent.com/3647850/128823082-24d0eea2-6db9-4640-96e8-9e1d134d7ffc.png)
