### ISSUE TITLE
Sub menu not expanded on clicking link

### ISSUE THREAD

**Issue by narze** [dotnetthailand/dotnetthailand.github.io#117]
https://user-images.githubusercontent.com/248741/128623407-ba5bef5d-6316-4485-893e-ebf436278ef7.mov

The submenu is not expanded when clicking on the text eg. `Testing > Jest`, while on the main menu it was expanded normally eg. `Testing`. Now I have to click at the `^` icon to expand the sub-menu.

**Comment by mildronize** [comment]
@narze  I see, thank you very much for your feedback. If it can be fixed, the UX is better :)
