### ISSUE TITLE
Adding Content for Blazor WASM

### ISSUE THREAD

**Issue by F0x45N** [dotnetthailand/dotnetthailand.github.io#123]
Not sure if Blazor or Web Assembly is welcome here or not, but I have some content about making a Web Application in Blazor WASM from my experience that wanna share. Wanna know if the Dotnet Thailand team would be interested?

**Comment by aaronamm** [comment]
Thank you for willing to help .NET Thailand community.
Brazor is part of .NET so your content will value to the community.

Please open a new PR with a new content in a Markdown file.
I suggest to create your topic under a new Brazor group.
For example:
Web Frameworks > Brazor > Your content

Thanks.

![image](https://user-images.githubusercontent.com/2938310/129486569-e62e2426-dc88-4dc2-a60f-0ef9e67746e7.png)

**Comment by F0x45N** [comment]
Alright, will probably be working on it during this upcoming weekend 👌

**Comment by aaronamm** [comment]
@F3nn1t0 I can't wait to read your content. 
Thanks.
