### ISSUE TITLE
[docs] Add AzureDevOps Content - getting start and structure article

### ISSUE THREAD

**Issue by sikiryl** [dotnetthailand/dotnetthailand.github.io#143]
I plan to add AzureDevOps contents in Azure section just like this
```
Cloud & Hosting
|-> Microsoft Azure
      |-> AzureDevOps
            |-> Getting Started (content)
            |-> Azure Boards
            |-> Azure Repos
            |-> Azure Pipelines
            |-> Azure Test Plans
            |-> Azure Artifacts
...

```

**Comment by aaronamm** [comment]
Since this issue has been resolved and we have devops contents in .NET Thailand.
It think it is okay to close this PR.

Thanks @Sikiryl for your contribution. 

![image](https://user-images.githubusercontent.com/2938310/136685328-8a620c91-e1a2-4863-8975-c29b330df92d.png)
