### ISSUE TITLE
Wow Amazing Work!

### ISSUE THREAD

**Issue by kidchenko** [dotnetthailand/dotnetthailand.github.io#22]
I checked the repository a few months ago and checked again today. I would like to say congratulations to all the team, It has been amazing work!!! Thank you a lot for pushing the .NET Community in Thailand! <3 <3 <3

**Comment by aaronamm** [comment]
@kidchenko Thank you so much mannn.
https://www.facebook.com/groups/dotnetthailand/permalink/3859006694185159/
