### ISSUE TITLE
Add an open graph meta tag to display logo of dotnetthailand

### ISSUE THREAD

**Issue by surrealist** [dotnetthailand/dotnetthailand.github.io#24]
### Problem
When post a link from dotnetthailand website to other sites (ex. Facebook)
it'll display Gastby logo but it should be dotnetthailand logo instead.

![image](https://user-images.githubusercontent.com/344784/114260177-637f6100-99fd-11eb-9757-2a46dd32d76d.png)

### Solution
Add `<meta>` tag for `og:image` to every pgaes of the site.

```html
<meta property="og:image" content="url.to/the/image" />
```

REF: https://ogp.me/

**Comment by aaronamm** [comment]
@surrealist Thanks for opening an issue and giving a good suggestion. 
BTW, we have AI logo but we are lack of graphic skill and CSS style. 
If someone can  help us for this, we would be appreciate it.

Here is a screenshot of AI logo file that we have.

![image](https://user-images.githubusercontent.com/2938310/114278638-f8fd0e00-9a5a-11eb-9e82-698ec8ee8811.png)

**Comment by mennwebs** [comment]
I volunteer for this. Tomorrow will check and PR krub.

**Comment by surrealist** [comment]
Thanks, @MennStudio. Let's me flag you as an assignee.

**Comment by mennwebs** [comment]
Sorry I can't PR right now. Then may be you guys just use these images instead? I create 3 versions of open graph to use. 

![og-img-1](https://user-images.githubusercontent.com/4017086/114571582-fb50a980-9ca0-11eb-9626-d589fd3473b2.png)

![og-img-2](https://user-images.githubusercontent.com/4017086/114571323-c6dced80-9ca0-11eb-8097-cc8d17cb8ad8.png)

![og-img-3](https://user-images.githubusercontent.com/4017086/114571339-cba1a180-9ca0-11eb-870f-17445f53d994.png)


And also the png logo.
![dotnet-logo](https://user-images.githubusercontent.com/4017086/114571429-dd834480-9ca0-11eb-8467-73f58a524bc4.png)

**Comment by surrealist** [comment]
@MennStudio Sorry that you cannot do pull request now. Anyway you already contributed to this issue by creating a very neat and high quality design images. Thanks again.

**Comment by aaronamm** [comment]
@MennStudio Thank you so much.

**Comment by surrealist** [comment]
We have 2 places that can inject meta og:image to html.
First one is src/html.js that need metadata:ogImage
from config/default.js. And the second one is
src/component/Soe/Soe.js this component need
metadata:siteImage from config/config.yml

I choose the second way (Soe.js) only then our web page
will have only one meta tag for og:image
