### ISSUE TITLE
Convert Roadmap items in Readme to Milestone

### ISSUE THREAD

**Issue by surrealist** [dotnetthailand/dotnetthailand.github.io#27]
Refresh items in roadmap and create milestones for them.

![image](https://user-images.githubusercontent.com/344784/114303539-c9044800-9af8-11eb-89f5-24c708c09810.png)

**Comment by aaronamm** [comment]
@surrealist  How do we create a milestone?

**Comment by surrealist** [comment]
![image](https://user-images.githubusercontent.com/344784/114686963-75cf0700-9d3d-11eb-8c20-4f1f813ca73f.png)

**Comment by surrealist** [comment]
As discussed in admin meeting today. Milestone is not need now.
