### ISSUE TITLE
Last update and author of article is incorrect

### ISSUE THREAD

**Issue by surrealist** [dotnetthailand/dotnetthailand.github.io#36]
## Problems
When navigating pages, we will see all the same last update date and author of the article, which is incorrect.

![image](https://user-images.githubusercontent.com/344784/114972298-759f4a80-9ea8-11eb-8cd0-2cf8a0db07eb.png)

## Expected Results
I suggest that the last update date/time should be the time of the last commit on that page. 
This will help readers to know how up-to-date the information 
for example 2 minutes ago and 2 years ago are very different.

The author's name should be all of the contributors of that page as we can see from the Microsoft Docs site.

![image](https://user-images.githubusercontent.com/344784/114973115-fc085c00-9ea9-11eb-9498-f306c4ee9423.png)

**Comment by kaiwanyawit-chawankul** [comment]
Start by updating this file src/templates/docs.js
now we use data from this plugin https://github.com/kraynel/gatsby-transformer-gitinfo/blob/master/src/gatsby-node.js
not sure modify the plugin is the right way
