### ISSUE TITLE
Dark background don't cover the whole content for the dark them 

### ISSUE THREAD

**Issue by RachaneeSaeng** [dotnetthailand/dotnetthailand.github.io#37]
Dark background don't cover the whole content if it is longer than a page.
<img width="1759" alt="image" src="https://user-images.githubusercontent.com/12830900/114975696-e5b0cf00-9eae-11eb-93c9-13625c69d980.png">

**Comment by aaronamm** [comment]
@RachaneeSaeng  I thought there is a problem only a mobile device.
