### ISSUE TITLE
Font color in dark theme not easy to read

### ISSUE THREAD

**Issue by surrealist** [dotnetthailand/dotnetthailand.github.io#47]
## Problem
In dark mode font color is red `rgb(228, 0, 70)` or `#E30048` when place 
on black or grey background is **not easy for reading**.

![image](https://user-images.githubusercontent.com/344784/115061220-175b8180-9f13-11eb-8088-f5746dffe7dc.png)

When test contrast level at [webaim.org](https://webaim.org/resources/contrastchecker), we got some tests failed.

![image](https://user-images.githubusercontent.com/344784/115061029-cea3c880-9f12-11eb-8271-a13dea6422b1.png)

## Expected Result
We should research a bit and pick a color scheme for the dark mode that gets a better readability score.

This can be good start [Best dark themes pack](https://marketplace.visualstudio.com/items?itemName=thegeoffstevens.best-dark-themes-pack) for example: 

### Dracula theme
![image](https://user-images.githubusercontent.com/344784/115062324-6f46b800-9f14-11eb-8533-9a6844d9aa97.png)

### Horizon theme
![image](https://user-images.githubusercontent.com/344784/115062521-a3ba7400-9f14-11eb-8fa1-b015f9045ccf.png)

🎈 Let's discuss, proposed, and choose together in this issue.

**Comment by mildronize** [comment]
I've done in PR #101 , I've made change to color blue: https://github.com/mildronize/dotnetthailand.github.io/blob/29e263777b9c06da83bd0b57340f9fa35f79991a/src/theme/dark.js#L6
