### ISSUE TITLE
Add  showcase/interesting projects that made with .NET

### ISSUE THREAD

**Issue by aaronamm** [dotnetthailand/dotnetthailand.github.io#50]
- We should have a page on .Thailand to list showcase projects or interesting projects that are made with .NET.
- Here are the example of interesting projects:
  - https://github.com/unnawut/awesome-thai-dev
  - https://github.com/vietnam-devs/coolstore-microservices
  - [Azure function for high request volume app case study](https://docs.google.com/document/d/17jXedypQI950Y3MXHrc3dZvrMF_puzDL5nvZKVkqS48/edit)
  - https://github.com/codesanook/thailand-regional-projects

CC @surrealist @execution

**Comment by surrealist** [comment]
I want to emphasize that we will provide an open space for Thai members to show up their .NET repository.
Big and small, advanced or beginner level, organization or individual, already famous or 1-commit repo, 
we are all welcome.

That space can surely include your above-referred repositories.

In other words, it's like [Friends of dotnet thailand](https://www.dotnetthailand.com/friends-of-dotnet-thailand) page
but a collection of **real .net repos** that built by **our members** (not their websites).

**Comment by aaronamm** [comment]
Thanks for adding useful information.

**Comment by aaronamm** [comment]
This PR is solve because @mildronize has created 📦 Awesome .NET Thailand Projects section already. 

![image](https://user-images.githubusercontent.com/2938310/139105406-d42547b2-2047-428e-8aad-00d9a444a2fd.png)

https://www.dotnetthailand.com/awesome-dotnet-thailand-projects/vb-dotnet/manipulate-virtual-keyboard
