### ISSUE TITLE
Move how to contribute to CONTRIBUTING.md

### ISSUE THREAD

**Issue by surrealist** [dotnetthailand/dotnetthailand.github.io#58]
Move [how to contribute](https://github.com/dotnetthailand/dotnetthailand.github.io#how-to-contribute-to-this-project) section of `readme.md` to a separate file `CONTRIBUTING.md`
to meet the standard of [GitHub community health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file).

There is more fun if we create a new repository in the organization named `.github`
and put CONTRIBUTING.md to use as a default community health file for a new repository.

**Comment by aaronamm** [comment]
@surrealist  I like your idea. 
I will create a repository with name `.github` and could you please continue working by pulling our contribution section in README.md to CONTRIBUTING.md, then put it in the root of .github repository?

You might need two PRs for this:
- Targeting dotnetthailand.github.io main branch
- Targeting .github main branch

After these PR merged, we should automatically see `CONTRIBUTING.md` to all repositories.

**Comment by aaronamm** [comment]
@surrealist  Our .github repository https://github.com/dotnetthailand/.github
