### ISSUE TITLE
Fix <a> color when using dark mode

### ISSUE THREAD

**Issue by kidchenko** [dotnetthailand/dotnetthailand.github.io#97]
When we are using the dark mode. the link colors aren't so legible. 

![image](https://user-images.githubusercontent.com/5432753/126540399-d987bfa4-ec9f-4769-8436-c165561934ad.png)

I would like to fix this issue since is an up-for-grabs and I am new contributing here.

The main goal with this issue is only to foster communication.

@aaronamm can we pair together on this?

**Comment by kidchenko** [comment]
#24
#34 

https://drive.google.com/file/d/1qqmAS0YPfDQcFWrzP0ITauzJw5IVIGl2/view

**Comment by aaronamm** [comment]
@kidchenko Is it possible for you to help fixing this issue.
Thanks.

**Comment by kidchenko** [comment]
Yes, I can fix it, just saw the comment today. I will start to work on this soon then.

**Comment by kidchenko** [comment]
@aaronamm do you have any labels we can add?
